IF DB_ID('Probando') IS NULL
BEGIN
    CREATE DATABASE Probando;
END
GO

USE Probando;
GO

CREATE TABLE Usuarios (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Nombre NVARCHAR(100) NOT NULL,
    Email NVARCHAR(200) NOT NULL UNIQUE
);
GO